project:
  type: website
  output-dir: docs

website:
  title: "Material de Apoyo para el Curso Aprendizaje y Comportamiento Adaptable"
  repo-url: https://github.com/Christian-F-Badillo/Simulaciones_Aprendizaje_y_Conducta_Adaptativa
  repo-branch: master
  sidebar:
    tools: 
      - icon: github
        href: https://github.com/BouzasLab25
    
    logo: img_general/Lab25_logo.png
    
    contents:
      - href: index.qmd
        text: Inicio
      - href: about.qmd
        text: Acerca
      
      - text: "---"
      
      - href: student_guide.qmd
        text: "Gu铆as de Estudio"
      - href: https://christian-badillo.quarto.pub/aprendizaje-comportamiento-adaptable-material-de-apoyo/
        text: "Materiales Anteriores"

      - text: "---"

      - section: "Teor铆a de Juegos"
        contents: GameTheory/*.qmd

      - section: "Redes Neuronales"
        contents: 
          - href: ANN/IntroANN.qmd
            text: "Introducci贸n a Redes Neuronales"
          - href: https://colab.research.google.com/drive/1HXWImo6sjqWgLHpTSArQF4-HzBUfUB6E?usp=sharing
            text: "Modelo de Memoria Sem谩ntica"
          - href: https://colab.research.google.com/drive/1SxFoFMpcCTFWkGuMAOOJsa9gYIhkFR0O?usp=sharing
            text: "Modelo de Memoria de Trabajo"
          - href: https://colab.research.google.com/drive/12Z9t0fRN5nE1KkNErYBMvyRLuHWsODvL?usp=sharing
            text: "Modelo de Memoria Epis贸dica"

      - section: "Modelos de Difusi贸n"
        contents: DifussionModels/*.qmd
      
      - section: "Aprendizaje por Refuerzo"
        contents:
          - href: https://colab.research.google.com/drive/1G67BzE4XWUSDK5_PwuDXEL6NhgzhLMke?usp=sharing
            text: "RL en Entornos Vol谩tiles y Estoc谩sticos"
      
      - section: "Categorizaci贸n"
        contents:
          - href: https://colab.research.google.com/drive/1Eak3NCf8eTB3FlHXt-RcBEfPTeQokgG8?usp=sharing
            text: "Modelo Contextual Generalizado"
      
      - section: "Modelos Bayesianos"
        contents:
          - href: https://christian-f-badillo-h.shinyapps.io/Regresion-Lineal-Bayesiana/
            text: "Ley de Igualaci贸n Generalizada"
      
      - section: "Curso de Python"
        contents:
          - href: https://christian-f-badillo.github.io/Ciencia-de-datos-con-Python-de-estadistica-descriptiva-a-redes-neuronales/
            text: "Ciencia de Datos con Pyhton"
  
  page-footer:
      border: true 
      center: "Sitio Web Creado por Christian Badillo con [Quarto](https://quarto.org) y  para el Lab25"
      left:
        - text: "Acerca"
          href: about.qmd
      right: 'Sitio Web Apoyado por el Proyecto [PAPIME](https://dgapa.unam.mx/index.php/fortalecimiento-a-la-docencia/papime): PE309624'

format:
  html:
    link-external-icon: false
    link-external-newwindow: true
    
    theme:
      light: cerulean
      dark: superhero
    
    lang: es
    css: styles.css
    toc: true
    toc-title: "Tabla de Contenido"
    toc-depth: 3
    code-line-numbers: true
    code-fold: true
    code-copy: true
    code-overflow: scroll
    code-tools:
      source: repo
      toggle: true
      caption: "Ver c贸digo"
    code-block-border-left: warning
    code-block-bg: false
    highlight-style: github
    code-link: false

    fig-align: center

    plotly-connected: true
    csl: apa.csl

execute: 
  cache: true
  echo: true
  output: true
  freeze: auto
  keep-ipynb: true
  kernel: python3